FROM nginx:latest
COPY default-second.conf /etc/nginx/conf.d/default.conf
ARG APP_BASE_PREFIX
RUN sed -i "s.%%prefix%%.$APP_BASE_PREFIX." /etc/nginx/conf.d/default.conf
COPY app/ /app
expose 80
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
